### PR TITLE
add russian translation; courtesy of bitzetov

### PR DESCRIPTION
**Pull request by cryptorex**

### CODE REVIEW

**Comment by cryptorex** [comment]
Please approve :)

**Comment by egyptianbman** [comment]
Hey, sorry -- there's a piece missing that ties it into the site. I'll add it tonight and do a deployment.

**Comment by cryptorex** [comment]
I see it - I will add.

**Comment by cryptorex** [comment]
maybe https://github.com/bitcoinz-sites/btcz.rocks/pull/50/commits/ecd5467855b5676e989476038713f7e195d43b16 will do it.. not sure how the 'icon' works couldn't see reference to it ... didn't look hard enough?

**Review by kovacbb — COMMENTED** [review]
icon for the land should be "ru", "rs" is serbia

**Comment by cryptorex** [comment]
thanks @kovacbb changed all to ru in https://github.com/bitcoinz-sites/btcz.rocks/pull/50/commits/82bf310cafbff8a87fded047e5265471a85ea17f

**Comment by egyptianbman** [comment]
It looks like the English side doesn't match. -- https://beta.btcz.rocks/?lang=ru

I've uploaded the document to https://docs.google.com/spreadsheets/d/1yeY6aPqWlkj8ZwA_UzxmHiHKQW51RKQEJjVQWWjAw7w/edit#gid=252604849 to give us a sharable source of truth for the translation if you want to share it with someone. Replacing the file in the commit is easy -- you can just file -> download as csv and overwrite the one in the code.

**Comment by egyptianbman** [comment]
@cryptorex I've already updated it to match what the site expects. I just need you to download the file as csv, replacing the file that's in there now. I'd do it for you but I can't push to your repository.

**Comment by cryptorex** [comment]
should be updated now.  I'm looking for the differences you were referring to.

**Review by egyptianbman — APPROVED** [review]
Thanks!

**Pull request merged**
