### PR TITLE
update main.css to include txtz documentation

### PR DESCRIPTION
**Pull request by Teku16**

### CODE REVIEW

**Comment by renuzit** [comment]
So, I see CSS changes, but no HTML changes, it feels like a few files are missing.

**Comment by renuzit** [comment]
I understand now. I see you have multiple changes in your branch. Can you please merge the two commits together? You can download the github desktop app to assist you. This lets you checkout the source code, make changes, and then save to git. Check it out here: https://desktop.github.com/

**Comment by Teku16** [comment]
Ahh yes, sorry my friend. I have never used Github with multiple people, and it has been a while since I used it at all! I will square it up tonight :-)

**Comment by renuzit** [comment]
Let me know if I can help!

**Pull request closed without merging**
