### PR TITLE
Added Serbian Language

### PR DESCRIPTION
**Pull request by EmptySD**

### CODE REVIEW

**Comment by kovacbb** [comment]
It looks OK, can we have a Serbian languge inside? tnx!

**Comment by EmptySD** [comment]
@kovacbb I got first comment that it's not complete. Is there anything else that need to be translated that i missed?
@egyptianbman Can this please be reviewed and added to website?

**Comment by egyptianbman** [comment]
FYI: I'm merging this and then will be restructuring the site and hooking everything up, thanks for your help!

**Comment by EmptySD** [comment]
@egyptianbman thanks. I saw fork for restructuring. If there's help needed i can join it.

**Comment by kovacbb** [comment]
@EmptySD I think there is a job for you with a new cool website version..? :)
https://beta.btcz.rocks/
Cheers!
Hvala!

**Comment by EmptySD** [comment]
@kovacbb oh new version is already up. I will check it out, thanks.

**Pull request merged**
