### PR TITLE
Fixed a misspelling and Swedish translated correct.

### PR DESCRIPTION
**Pull request by Lumiboy**

### CODE REVIEW

**Comment by egyptianbman** [comment]
Hey @Lumiboy thank you for providing these updates. Is this ready for review?

**Comment by Lumiboy** [comment]
It's ready :)

**Review by Lumiboy — COMMENTED** [review]
Ready!

**Review by egyptianbman — APPROVED** [review]
I don't speak Swedish but this looks OK to me.

**Pull request merged**
